version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - 5500:5500

  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    restart: always
    ports:
      - 4321:4321

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    restart: always
    ports:
      - 3001:3001

  redis:
    container_name: redis
    image: redis:latest # Use the latest official Redis image
    restart: always
    ports:
      - 6379:6379 # Expose Redis port
    volumes:
      - redis_data:/data # Mount a volume for Redis data persistence
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
#Possibly use later

volumes:
  db_data:
  redis_data:
